
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int If = 7;
  public static final int Menor = 11;
  public static final int Parentesis_c = 3;
  public static final int ERROR = 15;
  public static final int Parentesis_a = 2;
  public static final int EOF = 0;
  public static final int P_coma = 4;
  public static final int DobleIgual = 10;
  public static final int False = 9;
  public static final int Identificador = 5;
  public static final int error = 1;
  public static final int Mayor = 12;
  public static final int True = 8;
  public static final int Menor_Igual = 13;
  public static final int Numero = 6;
  public static final int Mayor_Igual = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Parentesis_a",
  "Parentesis_c",
  "P_coma",
  "Identificador",
  "Numero",
  "If",
  "True",
  "False",
  "DobleIgual",
  "Menor",
  "Mayor",
  "Menor_Igual",
  "Mayor_Igual",
  "ERROR"
  };
}

